import 'package:flutter/material.dart';

/// 共通で使うダッシュボードアイコンのマッピング。
const Map<String, IconData> kDashboardIcons = {
  'list_alt': Icons.list_alt,
  'edit_note': Icons.edit_note,
  'history': Icons.history,
  'settings': Icons.settings,
  'invoice': Icons.receipt_long,
  'customer': Icons.people,
  'product': Icons.inventory_2,
  'menu': Icons.menu,
  'analytics': Icons.analytics,
  'map': Icons.map,
  'master': Icons.storage,
  'qr': Icons.qr_code,
  'camera': Icons.camera_alt,
  'contact': Icons.contact_mail,
  'store': Icons.store,
  'warehouse': Icons.warehouse,
  'badge': Icons.badge,
  'request_quote': Icons.request_quote,
  'assignment_turned_in': Icons.assignment_turned_in,
  'assignment_return': Icons.assignment_return,
  'picture_as_pdf': Icons.picture_as_pdf,
  'playlist_add_check': Icons.playlist_add_check,
  'undo': Icons.undo,
  'payments': Icons.payments,
  'inventory': Icons.inventory,
  'compare_arrows': Icons.compare_arrows,
  'fact_check': Icons.fact_check,
  'tune': Icons.tune,
  'stacked_line_chart': Icons.stacked_line_chart,
  'show_chart': Icons.show_chart,
  'account_balance_wallet': Icons.account_balance_wallet,
  'admin_panel_settings': Icons.admin_panel_settings,
  'article': Icons.article,
};
